import React, { useEffect, useState } from "react";
import Card from "../card/Card";
import Loader from "../loaders/Loader";
import DetailedCard from "../card/DetailedCard";
import Head from "next/head";
import SearchInput from "./searchInput/SearchInput";

interface Character {
  name: string;
  birth_year: string;
  created: string;
  edited: string;
  eye_color: string;
  films: string[];
  gender: string;
  hair_color: string;
  height: string;
  homeworld: string;
  mass: string;
  skin_color: string;
  species: any[];
  starships: string[];
  url: string;
  vehicles: string[];
}

export default function Chars() {
  const [characters, setCharacters] = useState<Character[]>([]);
  const [selectedCharacter, setSelectedCharacter] = useState<Character | null>(
    null
  );
  const [searchQuery, setSearchQuery] = useState<string>("");
  const [characterData, setCharacterData] = useState([]);
  const [searchQueryFilm, setSearchQueryFilm] = useState("");
  const [searchQueryHomeworld, setSearchQueryHomeworld] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<any>();

  useEffect(() => {
    const fetchCharacters = async () => {
      try {
        const response = await fetch("/api/characters");

        if (!response.ok) {
          throw new Error(`HTTP error! Status: ${response.status}`);
        }
        const data = await response.json();
        setCharacters(data);
      } catch (error) {
        console.error("Error fetching data:", error);
        setError(error);
      }
    };

    const fetchCharacterDetail = async () => {
      try {
        const response = await fetch("/api/characterDetail");
        if (!response.ok) {
          throw new Error(`HTTP error! Status: ${response.status}`);
        }
        const data = await response.json();
        setCharacterData(data.data);
        setLoading(false);
      } catch (error) {
        console.error("Error fetching data:", error);
        setError(error);
      }
    };

    fetchCharacterDetail();
    fetchCharacters();
  }, []);

  const handleReadMore = (character: Character) => {
    setSelectedCharacter(character);
  };

  const handleBack = () => {
    setSelectedCharacter(null);
  };
  const handleNameSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchQuery(e.target.value);
  };

  const handleFilmSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchQueryFilm(e.target.value.toLowerCase());
  };

  const handleHomeworldSearchChange = (
    e: React.ChangeEvent<HTMLInputElement>
  ) => {
    setSearchQueryHomeworld(e.target.value.toLowerCase());
  };

  const handleNext = () => {
    const currentIndex = characters.findIndex(
      (character) => character.name === selectedCharacter?.name
    );
    const nextIndex = (currentIndex + 1) % characters.length;
    setSelectedCharacter(characters[nextIndex]);
  };

  const handlePrevious = () => {
    const currentIndex = characters.findIndex(
      (character) => character.name === selectedCharacter?.name
    );
    const prevIndex =
      (currentIndex - 1 + characters.length) % characters.length;
    setSelectedCharacter(characters[prevIndex]);
  };

  const filteredCharacters = characterData
    .filter((character: any) =>
      character.name.toLowerCase().includes(searchQuery.toLowerCase())
    )
    .filter((character: any) => {
      if (!searchQueryFilm) return true;
      return character.films.some((film: any) =>
        film.toLowerCase().includes(searchQueryFilm)
      );
    })
    .filter((character: any) => {
      if (!searchQueryHomeworld) return true;
      return character.homeworld.toLowerCase().includes(searchQueryHomeworld);
    });

  if (loading) {
    return <Loader />;
  }
  if (error) {
    return <div>Error: {error.message}</div>;
  }

  if (selectedCharacter) {
    return (
      <DetailedCard
        character={selectedCharacter}
        onBack={handleBack}
        onNext={handleNext}
        onPrevious={handlePrevious}
      />
    );
  }

  return (
    <div>
      <Head>
        <title>Star Wars Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <br />
      <br />
      <br />
      <div className="inputContainer">
        <SearchInput
          searchQuery={searchQuery}
          placeholder="Search by name"
          searchChange={handleNameSearchChange}
        />
        <SearchInput
          searchQuery={searchQueryFilm}
          placeholder="Search by film"
          searchChange={handleFilmSearchChange}
        />

        <SearchInput
          searchQuery={searchQueryHomeworld}
          placeholder="Search by homeworld"
          searchChange={handleHomeworldSearchChange}
        />
      </div>
      <div className="card-list">
        {filteredCharacters.map((filteredCharacter: any, index: any) => {
          const fullCharacterData = characters.find(
            (character) => character.name === filteredCharacter.name
          );

          return fullCharacterData ? (
            <div key={index}>
              <Card character={fullCharacterData} onReadMore={handleReadMore} />
            </div>
          ) : (
            <Loader />
          );
        })}
      </div>
      <br />
      <br />
      <br />
      <br />
    </div>
  );
}
